#!/usr/bin/env python3
"""Finalize clip-art provenance with checksums after SVG and PNG export."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
SET=ROOT/'assets'/'clip-art-set'
ASSETS=SET/'assets'
NAMES=['staffing-mix','classical-counterfactual','evidence-gate','quantum-pilot','independent-certificate','classical-fallback','outcome-ledger','difficulty-vector-instrument']
ROLES=['hero','instrument','process','instrument','process','risk','output','instrument']
STATUS=['conceptual-mechanism','verified-object','conceptual-mechanism','verified-object','conceptual-mechanism','conceptual-mechanism','conceptual-mechanism','conceptual-mechanism']
RELEASE_DATE='2026-08-18'

def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()

assets=[]
for name,role,status in zip(NAMES,ROLES,STATUS):
    svg=ASSETS/f'{name}.svg'; png=ASSETS/f'{name}.png'
    if not svg.exists() or not png.exists(): raise SystemExit(f'missing asset export: {name}')
    with Image.open(png) as im:
        im.load()
        if im.mode != 'RGBA' or im.getextrema()[3] == (255,255):
            raise SystemExit(f'asset PNG lacks a real alpha channel: {name}')
    assets.append({
        'id':name,'concept':name.replace('-',' '),'semantic_role':role,
        'source_locator':'authoritative paper brief and frozen Q-OPS architecture','evidence_status':status,
        'file':f'assets/{svg.name}','format':'svg','source_type':'original-vector',
        'description':f'Original editorial-vector illustration of {name.replace("-"," ")}.',
        'alt_text':f'Conceptual technical illustration for {name.replace("-"," ")}.',
        'visual_recipe':['native SVG geometry','front editorial view','rounded dark-ink outline','restrained named-role palette','transparent background'],
        'unsupported_implications':['measured effect','causal result','external certification','production readiness','fairness or welfare','quantum advantage'],
        'palette_roles':['ink','surface','primary','secondary','status_accent'],'viewpoint':'front editorial vector',
        'placement':{'preferred_panel':'architecture or evidence narrative','anchor':'center','target_print_width_mm':[18,25],'minimum_print_width_mm':12,'clear_space_percent':12,'background_compatibility':'light'},
        'geometry':{'viewbox':[0,0,512,512],'visible_bounds':[48,48,464,464],'optical_center':[256,256],'connector_safe_ports':{'north':[256,48],'east':[464,256],'south':[256,464],'west':[48,256]},'no_go_rectangle':[70,70,442,442]},
        'provenance':{'authoring_method':'Native SVG geometry generated by scripts/generate_release_assets.py','created_on':RELEASE_DATE,'editable_master':f'assets/{name}.svg'},
        'checksum_sha256':sha(svg),
        'derived_png':f'assets/{png.name}',
        'derived_png_checksum_sha256':sha(png),
    })
contact_png=SET/'contact-sheet.png'
contact_svg=SET/'contact-sheet.svg'
with Image.open(contact_png) as im:
    im.load()
    contact_dimensions=list(im.size)
manifest={
    'schema_version':'1.0','set_id':'qops-evidence-aware-clip-art-v1','title':'Q-OPS evidence-aware routing technical clip art',
    'purpose':'Restrained semantic illustrations for the application architecture and evidence narrative.',
    'source':{'kind':'paper','title':'Q-OPS evidence-aware revision','locator':'overleaf/main.tex and data/locked_c12_*'},
    'target_figure':{'type':'architecture and evidence workflow','background':'light','placement':'NeurIPS two-column manuscript, 25 mm minimum asset width'},
    'evidence_boundary':'Conceptual illustrations only. They do not encode measurements, causal effects, certification by an external body, implementation status, fairness, welfare, safety, or quantum advantage.',
    'build_order':'clip-art SVG -> transparent PNG previews -> decoded contact sheet -> checksummed manifest -> manuscript diagrams',
    'art_direction':{'mode':'editorial-vector','viewpoint':'front','outline':'dark ink, rounded joins, 2 px equivalent','lighting':'flat','detail_level':'medium','font_family':'Nimbus Sans / TeX Gyre Heros for editable diagram labels only','palette':{'ink':'#18324A','surface':'#F5F7FB','primary':'#315EFB','secondary':'#0F766E','caution':'#A94F21','boundary':'#8B4050','divider':'#CBD5E1'}},
    'hero_asset_id':'staffing-mix',
    'contact_sheet':{'png':'contact-sheet.png','svg':'contact-sheet.svg','dimensions_px':contact_dimensions,'png_checksum_sha256':sha(contact_png),'svg_checksum_sha256':sha(contact_svg),'decode_status':'PASS'},
    'assets':assets,
}
(SET/'clip-art-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print(f'finalized {len(assets)} asset records')
