#!/usr/bin/env python3
"""Finalize clip-art provenance with checksums after SVG and PNG export."""
from __future__ import annotations
import hashlib, json
from datetime import date
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SET=ROOT/'assets'/'clip-art-set'
ASSETS=SET/'assets'
NAMES=['staffing-mix','classical-counterfactual','evidence-gate','quantum-pilot','independent-certificate','classical-fallback','outcome-ledger']
ROLES=['hero','instrument','process','instrument','process','risk','output']
STATUS=['conceptual-mechanism','verified-object','conceptual-mechanism','verified-object','conceptual-mechanism','conceptual-mechanism','conceptual-mechanism']

def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()

assets=[]
for name,role,status in zip(NAMES,ROLES,STATUS):
    svg=ASSETS/f'{name}.svg'; png=ASSETS/f'{name}.png'
    if not svg.exists() or not png.exists(): raise SystemExit(f'missing asset export: {name}')
    assets.append({
        'id':name,'concept':name.replace('-',' '),'semantic_role':role,
        'source_locator':'authoritative paper brief and frozen Q-OPS architecture','evidence_status':status,
        'file':f'assets/{svg.name}','format':'svg','source_type':'original-vector',
        'description':f'Original editorial-vector illustration of {name.replace("-"," ")}.',
        'alt_text':f'Conceptual technical illustration for {name.replace("-"," ")}.',
        'visual_recipe':['native SVG geometry','front editorial view','rounded dark-ink outline','restrained named-role palette','transparent background'],
        'unsupported_implications':['measured effect','causal result','external certification','production readiness','fairness or welfare','quantum advantage'],
        'palette_roles':['ink','surface','primary','secondary','status_accent'],'viewpoint':'front editorial vector',
        'placement':{'preferred_panel':'architecture or evidence narrative','anchor':'center','min_width_px':180,'clear_space_percent':12,'background_compatibility':'light'},
        'provenance':{'authoring_method':'Native SVG geometry generated by scripts/generate_release_assets.py','created_on':str(date.today()),'editable_master':f'assets/{name}.svg'},
        'checksum_sha256':sha(svg),
        'derived_png':f'assets/{png.name}',
        'derived_png_checksum_sha256':sha(png),
    })
manifest={
    'schema_version':'1.0','set_id':'qops-evidence-aware-clip-art-v1','title':'Q-OPS evidence-aware routing technical clip art',
    'purpose':'Restrained semantic illustrations for the application architecture and evidence narrative.',
    'source':{'kind':'paper','title':'Q-OPS evidence-aware revision','locator':'overleaf/main.tex and data/locked_c12_*'},
    'target_figure':{'type':'architecture and evidence workflow','background':'light','placement':'NeurIPS two-column manuscript, 25 mm minimum asset width'},
    'evidence_boundary':'Conceptual illustrations only. They do not encode measurements, causal effects, certification by an external body, implementation status, fairness, welfare, safety, or quantum advantage.',
    'art_direction':{'mode':'editorial-vector','viewpoint':'front','outline':'dark ink, rounded joins, 2 px equivalent','lighting':'flat','detail_level':'medium','palette':{'ink':'#18324A','surface':'#F5F7FB','primary':'#315EFB','secondary':'#14877D','status_accent':'#D97745','divider':'#CBD5E1'}},
    'hero_asset_id':'staffing-mix','contact_sheet':'contact-sheet.png','assets':assets,
}
(SET/'clip-art-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print(f'finalized {len(assets)} asset records')
